# Generated by Django 4.2 on 2023-12-05 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserAdrees',
        ),
        migrations.DeleteModel(
            name='UserPhone',
        ),
    ]
